version: '3'
services:
    web:
        build:
            context: .
        ports:
        - "5000:5000"
    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
            MONGO_INITDB_DATABASE: notifications